"""Stable identifiers for discovery rights, opportunities, and governed rules."""

PERSONAL_ALLOWANCE = "TH-RIGHT-PERSONAL-ALLOWANCE"
PARENT_ALLOWANCE = "TH-RIGHT-PARENT-ALLOWANCE"
CHILD_ALLOWANCE = "TH-RIGHT-CHILD-ALLOWANCE"
SOCIAL_SECURITY = "TH-RIGHT-SOCIAL-SECURITY"
MORTGAGE_INTEREST = "TH-RIGHT-MORTGAGE-INTEREST"
RETIREMENT_SHARED_CAPACITY = "TH-RIGHT-RETIREMENT-SHARED-CAPACITY"
THAI_ESG = "TH-OPP-THAI-ESG-2026"
ARTWORK = "TH-OPP-ARTWORK-2025-2027"
SOLAR_ROOFTOP = "TH-OPP-SOLAR-ROOFTOP-2026"

EXISTING_RIGHT_IDS = (
    PERSONAL_ALLOWANCE,
    PARENT_ALLOWANCE,
    CHILD_ALLOWANCE,
    SOCIAL_SECURITY,
    MORTGAGE_INTEREST,
    RETIREMENT_SHARED_CAPACITY,
)
NEW_CASH_IDS = (THAI_ESG, ARTWORK, SOLAR_ROOFTOP)
ALL_DEFINITION_IDS = EXISTING_RIGHT_IDS + NEW_CASH_IDS

THAI_ESG_RULE = "TH-OPP-RULE-THAI-ESG-2026"
ARTWORK_RULE = "TH-OPP-RULE-ARTWORK-2025-2027"
SOLAR_ROOFTOP_RULE = "TH-OPP-RULE-SOLAR-ROOFTOP-805"
THAI_ESG_2026_POOL = "THAI_ESG_2026_POOL"

NEW_CASH_RULE_BY_ID = {
    THAI_ESG: THAI_ESG_RULE,
    ARTWORK: ARTWORK_RULE,
    SOLAR_ROOFTOP: SOLAR_ROOFTOP_RULE,
}
