"""Stable machine-readable reason codes shared by FinancialState and GuardrailResult."""

from __future__ import annotations

from enum import StrEnum


class FinancialReasonCode(StrEnum):
    EXISTING_RIGHT_PASSTHROUGH = "EXISTING_RIGHT_PASSTHROUGH"

    FINANCIAL_INPUT_REQUIRED = "FINANCIAL_INPUT_REQUIRED"

    EMERGENCY_FUND_BELOW_FLOOR = "EMERGENCY_FUND_BELOW_FLOOR"
    EMERGENCY_FUND_PRESERVED = "EMERGENCY_FUND_PRESERVED"
    ZERO_ESSENTIAL_EXPENSE_BASE = "ZERO_ESSENTIAL_EXPENSE_BASE"

    CRITICAL_DEBT_PRESENT = "CRITICAL_DEBT_PRESENT"

    LIQUIDITY_COMMITMENT_CONFLICT = "LIQUIDITY_COMMITMENT_CONFLICT"
    ALLOCATION_CAPPED_BY_LIQUIDITY = "ALLOCATION_CAPPED_BY_LIQUIDITY"
    NO_SPENDABLE_SURPLUS = "NO_SPENDABLE_SURPLUS"

    PROTECTION_GAP = "PROTECTION_GAP"
    PROTECTION_NEED_UNKNOWN = "PROTECTION_NEED_UNKNOWN"

    UPSTREAM_NOT_AVAILABLE = "UPSTREAM_NOT_AVAILABLE"
    GUARDRAIL_POLICY_NOT_READY = "GUARDRAIL_POLICY_NOT_READY"
