"""Stable identifiers for every material rule used by the phase-1 engine."""

PIT_RATE_SCHEDULE = "TH-PIT-RATE-SCHEDULE"
SECTION_40_1_EXPENSE = "TH-PIT-EXPENSE-40-1"
PERSONAL_ALLOWANCE = "TH-PIT-ALLOWANCE-PERSONAL"
SOCIAL_SECURITY_SECTION_33 = "TH-PIT-ALLOWANCE-SSO-33"
PARENT_ALLOWANCE = "TH-PIT-ALLOWANCE-PARENT"
CHILD_ALLOWANCE = "TH-PIT-ALLOWANCE-CHILD"
MORTGAGE_INTEREST = "TH-PIT-ALLOWANCE-MORTGAGE-INTEREST"
RETIREMENT_SHARED_LIMIT = "TH-PIT-LIMIT-RETIREMENT-SHARED"

ALL_RULE_IDS = (
    PIT_RATE_SCHEDULE,
    SECTION_40_1_EXPENSE,
    PERSONAL_ALLOWANCE,
    SOCIAL_SECURITY_SECTION_33,
    PARENT_ALLOWANCE,
    CHILD_ALLOWANCE,
    MORTGAGE_INTEREST,
    RETIREMENT_SHARED_LIMIT,
)
